[project]
dependencies = []
description = "Simplified demo of uv workspace editable deps bug"
name = "demo-cli"
readme = "README.md"
requires-python = ">=3.10, <3.13"
version = "0.1.0"

[project.scripts]
repro-demo-entrypoint = "demo_cli.main:run_cli"
